---

apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.56.10"
  bindPort: 6443

---

apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  dnsDomain: "vagrant-cluster.local"
  podSubnet: 192.168.0.0/16,2001:db8:42:0::/56
  serviceSubnet: 192.168.10.0/16,2001:db8:42:1::/112

---

apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs

---